const nicknameToIdMap: { [nickname: string]: number } = {
  "Dallas Cowboys": 1,
  "New York Giants": 2,
  "Philadelphia Eagles": 3,
  "Washington Football Team": 4,
  "Chicago Bears": 5,
  "Detroit Lions": 6,
  "Green Bay Packers": 7,
  "Minnesota Vikings": 8,
  "Atlanta Falcons": 9,
  "Carolina Panthers": 10,
  "New Orleans Saints": 11,
  "Tampa Bay Buccaneers": 12,
  "Arizona Cardinals": 13,
  "Los Angeles Rams": 14,
  "San Francisco 49ers": 15,
  "Seattle Seahawks": 16,
  "Kansas City Chiefs": 17,
  "Baltimore Ravens": 18,
  "Cincinnati Bengals": 19,
  "Cleveland Browns": 20,
  "Pittsburgh Steelers": 21,
  "Buffalo Bills": 22,
  "Miami Dolphins": 23,
  "New England Patriots": 24,
  "New York Jets": 25,
  "Houston Texans": 26,
  "Indianapolis Colts": 27,
  "Jacksonville Jaguars": 28,
  "Tennessee Titans": 29,
  "Denver Broncos": 30,
  "Las Vegas Raiders": 31,
  "Los Angeles Chargers": 32,
};

const idToNicknameMap: { [id: number]: string } = {
  1: "Dallas Cowboys",
  2: "New York Giants",
  3: "Philadelphia Eagles",
  4: "Washington Football Team",
  5: "Chicago Bears",
  6: "Detroit Lions",
  7: "Green Bay Packers",
  8: "Minnesota Vikings",
  9: "Atlanta Falcons",
  10: "Carolina Panthers",
  11: "New Orleans Saints",
  12: "Tampa Bay Buccaneers",
  13: "Arizona Cardinals",
  14: "Los Angeles Rams",
  15: "San Francisco 49ers",
  16: "Seattle Seahawks",
  17: "Kansas City Chiefs",
  18: "Baltimore Ravens",
  19: "Cincinnati Bengals",
  20: "Cleveland Browns",
  21: "Pittsburgh Steelers",
  22: "Buffalo Bills",
  23: "Miami Dolphins",
  24: "New England Patriots",
  25: "New York Jets",
  26: "Houston Texans",
  27: "Indianapolis Colts",
  28: "Jacksonville Jaguars",
  29: "Tennessee Titans",
  30: "Denver Broncos",
  31: "Las Vegas Raiders",
  32: "Los Angeles Chargers",
};

const nicknameToAbbrMap: { [nickname: string]: string } = {
  "Dallas Cowboys": "DAL",
  "New York Giants": "NYG",
  "Philadelphia Eagles": "PHI",
  "Washington Football Team": "WAS",
  "Chicago Bears": "CHI",
  "Detroit Lions": "DET",
  "Green Bay Packers": "GB",
  "Minnesota Vikings": "MIN",
  "Atlanta Falcons": "ATL",
  "Carolina Panthers": "CAR",
  "New Orleans Saints": "NO",
  "Tampa Bay Buccaneers": "TB",
  "Arizona Cardinals": "ARI",
  "Los Angeles Rams": "LAR",
  "San Francisco 49ers": "SF",
  "Seattle Seahawks": "SEA",
  "Kansas City Chiefs": "KC",
  "Baltimore Ravens": "BAL",
  "Cincinnati Bengals": "CIN",
  "Cleveland Browns": "CLE",
  "Pittsburgh Steelers": "PIT",
  "Buffalo Bills": "BUF",
  "Miami Dolphins": "MIA",
  "New England Patriots": "NE",
  "New York Jets": "NYJ",
  "Houston Texans": "HOU",
  "Indianapolis Colts": "IND",
  "Jacksonville Jaguars": "JAX",
  "Tennessee Titans": "TEN",
  "Denver Broncos": "DEN",
  "Las Vegas Raiders": "LV",
  "Los Angeles Chargers": "LAC",
};

export {nicknameToIdMap, idToNicknameMap, nicknameToAbbrMap};
