const nicknameToIdMap: { [nickname: string]: number } = {
  "Dallas Cowboys": 1,
  "New York Giants": 2,
  "Philadelphia Eagles": 3,
  "Washington Football Team": 4,
  "Chicago Bears": 5,
  "Detroit Lions": 6,
  "Green Bay Packers": 7,
  "Minnesota Vikings": 8,
  "Atlanta Falcons": 9,
  "Carolina Panthers": 10,
  "New Orleans Saints": 11,
  "Tampa Bay Buccaneers": 12,
  "Arizona Cardinals": 13,
  "Los Angeles Rams": 14,
  "San Francisco 49ers": 15,
  "Seattle Seahawks": 16,
  "Kansas City Chiefs": 17,
  "Baltimore Ravens": 18,
  "Cincinnati Bengals": 19,
  "Cleveland Browns": 20,
  "Pittsburgh Steelers": 21,
  "Buffalo Bills": 22,
  "Miami Dolphins": 23,
  "New England Patriots": 24,
  "New York Jets": 25,
  "Houston Texans": 26,
  "Indianapolis Colts": 27,
  "Jacksonville Jaguars": 28,
  "Tennessee Titans": 29,
  "Denver Broncos": 30,
  "Las Vegas Raiders": 31,
  "Los Angeles Chargers": 32,
};

export default nicknameToIdMap;
