type TeamNames =
  | "Dallas Cowboys"
  | "New York Giants"
  | "Philadelphia Eagles"
  | "Washington Football Team"
  | "Chicago Bears"
  | "Detroit Lions"
  | "Green Bay Packers"
  | "Minnesota Vikings"
  | "Atlanta Falcons"
  | "Carolina Panthers"
  | "New Orleans Saints"
  | "Tampa Bay Buccaneers"
  | "Arizona Cardinals"
  | "Los Angeles Rams"
  | "San Francisco 49ers"
  | "Seattle Seahawks"
  | "Kansas City Chiefs"
  | "Baltimore Ravens"
  | "Cincinnati Bengals"
  | "Cleveland Browns"
  | "Pittsburgh Steelers"
  | "Buffalo Bills"
  | "Miami Dolphins"
  | "New England Patriots"
  | "New York Jets"
  | "Houston Texans"
  | "Indianapolis Colts"
  | "Jacksonville Jaguars"
  | "Tennessee Titans"
  | "Denver Broncos"
  | "Las Vegas Raiders"
  | "Los Angeles Chargers";
